#!/bin/bash

if [ -z "$1" ]; then
  echo "Usage: $0 <ip-address> [download-directory | --upload=<file>]"
  exit 1
fi

# Check if the second argument is to upload a file
if [[ "$2" == --upload=* || "$2" == -u=* ]]; then
  # Extract the file to upload
  file_to_upload="${2#*=}"
  
  # Check if the file exists
  if [ ! -f "$file_to_upload" ]; then
    echo "The file $file_to_upload does not exist."
    exit 1
  fi
  
  # Execute the curl command to upload the file
  curl "http://$1/upload" \
    -X POST \
    -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0' \
    -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/jxl,image/webp,*/*;q=0.8' \
    -H 'Accept-Language: es-MX,es;q=0.8,en-US;q=0.5,en;q=0.3' \
    -H 'Accept-Encoding: gzip, deflate' \
    -H 'Content-Type: multipart/form-data' \
    -H "Origin: http://$1" \
    -H 'Sec-GPC: 1' \
    -H 'Connection: keep-alive' \
    -H "Referer: http://$1/index.html" \
    -H 'Upgrade-Insecure-Requests: 1' \
    -H 'Pragma: no-cache' \
    -H 'Cache-Control: no-cache' \
    -F "content=@$file_to_upload"
  
  exit 0
fi

# Use the second argument as the download directory if provided
if [ -n "$2" ]; then
  download_dir="$2"
else
  download_dir=$(xdg-user-dir DOWNLOAD)

  # Check if xdg-user-dir command is available and obtained the directory
  if [ $? -ne 0 ] || [ -z "$download_dir" ]; then
    echo "Could not determine the download directory. Use a second argument to specify it."
    exit 1
  fi
fi

# Create the download directory if it doesn't exist
mkdir -p "$download_dir"

# Clean up temporary files
rm -f /tmp/index.html /tmp/links.txt /tmp/names.txt

# Download the page
curl -s "http://$1/index.html" > /tmp/index.html

# Extract the links and their names
cat /tmp/index.html | pup 'div.card-body a attr{href}' > /tmp/links.txt
cat /tmp/links.txt | sed 's:.*/::' > /tmp/names.txt

# Use fzf to select a name
selected_name=$(cat /tmp/names.txt | fzf --prompt="Trebleshot CLI Downloader by ImJony: ")

# Check if a name was selected or if the operation was canceled
if [ -z "$selected_name" ]; then
  clear
  echo "Operation canceled. No file selected for download."
  rm -f /tmp/index.html /tmp/links.txt /tmp/names.txt
  exit 0
fi

# Find the link corresponding to the selected name
selected_index=$(grep -n "$selected_name" /tmp/names.txt | cut -d: -f1)
selected_link=$(sed -n "${selected_index}p" /tmp/links.txt)

# Download the file using wget, letting `wget` handle the file name and extension
wget --content-disposition -P "$download_dir" "http://$1$selected_link"

# Clean up temporary files
rm -f /tmp/index.html /tmp/links.txt /tmp/names.txt

# Option to run another command, such as `trebleshot`
sleep 1
trebleshot $1
